### ISSUE TITLE
DocHub (wrong?) link 

### ISSUE THREAD

**Issue by undavide** [ExtendScript/wiki#3]
The link in the `wiki/References-And-Links` to DocHub points to a .io domain that appears to be empty / for sale – not sure what the actual link should be (.com?)

**Comment by mhulse** [comment]
Looks like it's been down for a while. Here's the last record of it via WayBack:

https://web.archive.org/web/20141016022040/http://dochub.io/

From that page I found the GitHub repo:

https://github.com/rgarcia/dochub/issues

Looks like there's an issue:

https://github.com/rgarcia/dochub/issues/49

… their twitter feed has been inactive for a while:

https://twitter.com/documenthub

With that said, I am not sure of what a good replacement link would be as I don't know what dochub.io offered … Maybe this:

https://searchyapp.io/scopes/web-developer

This one also is interesting, though, probably not the same as dochub;

https://searchcode.com/

So, should we just remove the link? Can anyone think of a replacement site?

**Comment by ff6347** [comment]
I actually can't remember what doc hub was. Some kind of reference
