### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by andyinabox** [ExtendScript/wiki#4]
This is the part I'm struggling most with currently. If somebody is able to write up a few pointers on debugging ExtendScript projects that would be super helpful.

**Comment by ff6347** [comment]
Yes. This would useful.  

I tend to use a lot `of $.writeln()` statements, sometimes the ESTK breakpoints and the build in Databrowser and of course the Object Model viewer. From time to time I also use these functions:  

```javascript

function prop (f) {
  $.writeln(f.reflect.name);
  var props = f.reflect.properties;
  var array = [];
  for (var i = 0; i < props.length; i++) {
    try {
      array.push(props[i].name + ': ' + f[props[i].name]);
    } catch (_) {}
    array.sort();
  }
  $.writeln(array.join('\r'));
}
function meth (m) {
  var props = m.reflect.methods.sort();
  $.writeln('\rMethods');
  for (var i = 0; i < props.length; i++) {
    $.writeln(props[i].name);
  }
}

```
They write out all properties and methods of passed objects.  

They are taken from Peter Kahrels excellent [Script UI For Dummies](http://www.kahrel.plus.com/indesign/scriptui.html) 

But a bit longer article about it would be good.

**Comment by EugenTepin** [comment]
I use `$.writeln()` combined with `.toSource()` method of variable that need to be inspected.
